# Generated by Django 4.2 on 2023-08-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='笔名')),
                ('icon', models.CharField(max_length=255, verbose_name='头像')),
                ('introduction', models.CharField(default='新人', max_length=30, verbose_name='简介')),
                ('book_total', models.IntegerField(default=0, verbose_name='作品数')),
                ('all_word', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='总字数(万)')),
                ('start_work', models.IntegerField(default=0, verbose_name='创作天数')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='书名')),
                ('book_icon', models.CharField(max_length=255, verbose_name='封面')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('prop', models.SmallIntegerField(choices=[(1, '免费'), (2, 'VIP')], verbose_name='属性')),
                ('type', models.CharField(max_length=10, verbose_name='书的种类大')),
                ('category', models.CharField(max_length=30, verbose_name='书的类型小')),
                ('word', models.CharField(max_length=30, verbose_name='字数')),
                ('brief', models.CharField(default='这个人很懒，还没有写简介', max_length=255, verbose_name='简介')),
                ('collection', models.BooleanField(default=False, verbose_name='收藏')),
                ('recommend', models.BigIntegerField(verbose_name='推荐票')),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, to='web.authors', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='MonthTicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick_seq', models.CharField(max_length=30, unique=True, verbose_name='票号')),
                ('datetime', models.DateTimeField(verbose_name='投票日期')),
                ('voteuser', models.ForeignKey(db_column='voteuser', on_delete=django.db.models.deletion.DO_NOTHING, to='web.userinfo', verbose_name='投票人')),
                ('votework', models.ForeignKey(db_column='votework', on_delete=django.db.models.deletion.DO_NOTHING, to='web.books', verbose_name='投票作品')),
            ],
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_num', models.PositiveIntegerField(blank=0, verbose_name='收藏数')),
                ('bookname', models.ForeignKey(db_column='bookname', on_delete=django.db.models.deletion.CASCADE, to='web.books', verbose_name='书名')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='month_tick',
            field=models.ForeignKey(db_column='month_tick', on_delete=django.db.models.deletion.CASCADE, to='web.monthticks', verbose_name='月票'),
        ),
    ]
