# Generated by Django 4.2 on 2023-08-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='collection',
        ),
        migrations.CreateModel(
            name='MyViewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.BooleanField(default=False, verbose_name='收藏')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='阅读时间')),
                ('book', models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='web.books', verbose_name='收藏作品')),
                ('name', models.OneToOneField(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='用户')),
            ],
        ),
    ]
