# Generated by Django 4.2 on 2023-08-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='all_word',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='总字数(万)'),
        ),
    ]
