# Generated by Django 4.2 on 2023-08-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_books_collection_myviewbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myviewbook',
            name='name',
        ),
        migrations.AddField(
            model_name='myviewbook',
            name='user',
            field=models.OneToOneField(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
