# Generated by Django 4.2 on 2023-08-21 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_authors_all_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='introduction',
            field=models.CharField(default='新人', max_length=255, verbose_name='简介'),
        ),
    ]
