# Generated by Django 4.2 on 2023-08-21 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_authors_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='month_tick',
        ),
    ]
