# Generated by Django 4.2 on 2023-08-27 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_myviewbook_name_myviewbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myviewbook',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to='web.userinfo', verbose_name='用户'),
        ),
    ]
