# Generated by Django 4.2 on 2023-08-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_books_month_tick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='brief',
            field=models.TextField(default='这个人很懒，还没有写简介', verbose_name='简介'),
        ),
    ]
