# Generated by Django 4.2 on 2023-08-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_authors_last_login_authors_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='password',
        ),
    ]
